# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_vbw', [dirname(__file__)])
        except ImportError:
            import _vbw
            return _vbw
        if fp is not None:
            try:
                _mod = imp.load_module('_vbw', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _vbw = swig_import_helper()
    del swig_import_helper
else:
    import _vbw
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class block(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, block, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, block, name)
    __repr__ = _swig_repr
    __swig_setmethods__["size"] = _vbw.block_size_set
    __swig_getmethods__["size"] = _vbw.block_size_get
    if _newclass:
        size = _swig_property(_vbw.block_size_get, _vbw.block_size_set)
    __swig_setmethods__["alphas"] = _vbw.block_alphas_set
    __swig_getmethods__["alphas"] = _vbw.block_alphas_get
    if _newclass:
        alphas = _swig_property(_vbw.block_alphas_get, _vbw.block_alphas_set)
    __swig_setmethods__["saxsExpPtr"] = _vbw.block_saxsExpPtr_set
    __swig_getmethods__["saxsExpPtr"] = _vbw.block_saxsExpPtr_get
    if _newclass:
        saxsExpPtr = _swig_property(_vbw.block_saxsExpPtr_get, _vbw.block_saxsExpPtr_set)
    __swig_setmethods__["saxsErrPtr"] = _vbw.block_saxsErrPtr_set
    __swig_getmethods__["saxsErrPtr"] = _vbw.block_saxsErrPtr_get
    if _newclass:
        saxsErrPtr = _swig_property(_vbw.block_saxsErrPtr_get, _vbw.block_saxsErrPtr_set)
    __swig_setmethods__["saxsPrePtr"] = _vbw.block_saxsPrePtr_set
    __swig_getmethods__["saxsPrePtr"] = _vbw.block_saxsPrePtr_get
    if _newclass:
        saxsPrePtr = _swig_property(_vbw.block_saxsPrePtr_get, _vbw.block_saxsPrePtr_set)
    __swig_setmethods__["saxsMixPtr"] = _vbw.block_saxsMixPtr_set
    __swig_getmethods__["saxsMixPtr"] = _vbw.block_saxsMixPtr_get
    if _newclass:
        saxsMixPtr = _swig_property(_vbw.block_saxsMixPtr_get, _vbw.block_saxsMixPtr_set)
    __swig_setmethods__["saxsScale"] = _vbw.block_saxsScale_set
    __swig_getmethods__["saxsScale"] = _vbw.block_saxsScale_get
    if _newclass:
        saxsScale = _swig_property(_vbw.block_saxsScale_get, _vbw.block_saxsScale_set)
    __swig_setmethods__["numberProcs"] = _vbw.block_numberProcs_set
    __swig_getmethods__["numberProcs"] = _vbw.block_numberProcs_get
    if _newclass:
        numberProcs = _swig_property(_vbw.block_numberProcs_get, _vbw.block_numberProcs_set)
    __swig_setmethods__["OligomericSpecies"] = _vbw.block_OligomericSpecies_set
    __swig_getmethods__["OligomericSpecies"] = _vbw.block_OligomericSpecies_get
    if _newclass:
        OligomericSpecies = _swig_property(_vbw.block_OligomericSpecies_get, _vbw.block_OligomericSpecies_set)
    __swig_setmethods__["Concentration"] = _vbw.block_Concentration_set
    __swig_getmethods__["Concentration"] = _vbw.block_Concentration_get
    if _newclass:
        Concentration = _swig_property(_vbw.block_Concentration_get, _vbw.block_Concentration_set)
    __swig_setmethods__["MonomerMass"] = _vbw.block_MonomerMass_set
    __swig_getmethods__["MonomerMass"] = _vbw.block_MonomerMass_get
    if _newclass:
        MonomerMass = _swig_property(_vbw.block_MonomerMass_get, _vbw.block_MonomerMass_set)
    __swig_setmethods__["OligomerOrder"] = _vbw.block_OligomerOrder_set
    __swig_getmethods__["OligomerOrder"] = _vbw.block_OligomerOrder_get
    if _newclass:
        OligomerOrder = _swig_property(_vbw.block_OligomerOrder_get, _vbw.block_OligomerOrder_set)
    __swig_setmethods__["numberOfCurves"] = _vbw.block_numberOfCurves_set
    __swig_getmethods__["numberOfCurves"] = _vbw.block_numberOfCurves_get
    if _newclass:
        numberOfCurves = _swig_property(_vbw.block_numberOfCurves_get, _vbw.block_numberOfCurves_set)
    __swig_setmethods__["saxsWeightsEns"] = _vbw.block_saxsWeightsEns_set
    __swig_getmethods__["saxsWeightsEns"] = _vbw.block_saxsWeightsEns_get
    if _newclass:
        saxsWeightsEns = _swig_property(_vbw.block_saxsWeightsEns_get, _vbw.block_saxsWeightsEns_set)
    __swig_setmethods__["wCurrent"] = _vbw.block_wCurrent_set
    __swig_getmethods__["wCurrent"] = _vbw.block_wCurrent_get
    if _newclass:
        wCurrent = _swig_property(_vbw.block_wCurrent_get, _vbw.block_wCurrent_set)
    __swig_setmethods__["wCurrentPrim"] = _vbw.block_wCurrentPrim_set
    __swig_getmethods__["wCurrentPrim"] = _vbw.block_wCurrentPrim_get
    if _newclass:
        wCurrentPrim = _swig_property(_vbw.block_wCurrentPrim_get, _vbw.block_wCurrentPrim_set)
    __swig_setmethods__["alphaL"] = _vbw.block_alphaL_set
    __swig_getmethods__["alphaL"] = _vbw.block_alphaL_get
    if _newclass:
        alphaL = _swig_property(_vbw.block_alphaL_get, _vbw.block_alphaL_set)

    def __init__(self):
        this = _vbw.new_block()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _vbw.delete_block
    __del__ = lambda self: None
block_swigregister = _vbw.block_swigregister
block_swigregister(block)


def block_alloc(n):
    return _vbw.block_alloc(n)
block_alloc = _vbw.block_alloc

def block_free(t):
    return _vbw.block_free(t)
block_free = _vbw.block_free

def block_copy(inp, outp):
    return _vbw.block_copy(inp, outp)
block_copy = _vbw.block_copy

def block_copy_construct(xp):
    return _vbw.block_copy_construct(xp)
block_copy_construct = _vbw.block_copy_construct

def block_destroy(xp):
    return _vbw.block_destroy(xp)
block_destroy = _vbw.block_destroy

def ientropy(w, k):
    return _vbw.ientropy(w, k)
ientropy = _vbw.ientropy

def jensen_shannon_div(w_a, w_b, k):
    return _vbw.jensen_shannon_div(w_a, w_b, k)
jensen_shannon_div = _vbw.jensen_shannon_div

def polySolver(order, cmass_ratio, oligomeric_states, kconsts, roots):
    return _vbw.polySolver(order, cmass_ratio, oligomeric_states, kconsts, roots)
polySolver = _vbw.polySolver

def find_poly_root(w_ens, w_ens_prim, ct, ct_prim, monomerMass, k, order, oligomeric_species):
    return _vbw.find_poly_root(w_ens, w_ens_prim, ct, ct_prim, monomerMass, k, order, oligomeric_species)
find_poly_root = _vbw.find_poly_root

def SaxsScaleMean(saxs_ens, saxs_exp, err_saxs, N):
    return _vbw.SaxsScaleMean(saxs_ens, saxs_exp, err_saxs, N)
SaxsScaleMean = _vbw.SaxsScaleMean

def SaxsScaleStandardDeviation(saxs_ens, saxs_exp, err_saxs, N, T):
    return _vbw.SaxsScaleStandardDeviation(saxs_ens, saxs_exp, err_saxs, N, T)
SaxsScaleStandardDeviation = _vbw.SaxsScaleStandardDeviation

def L_function(xp):
    return _vbw.L_function(xp)
L_function = _vbw.L_function

def L_distance(xp, yp):
    return _vbw.L_distance(xp, yp)
L_distance = _vbw.L_distance

def L_print(xp):
    return _vbw.L_print(xp)
L_print = _vbw.L_print

def L_take_step(r, xp, step_size):
    return _vbw.L_take_step(r, xp, step_size)
L_take_step = _vbw.L_take_step

def run_vbw(again, k, mdfile, N, presaxsfile, Ncurves, curvesfile, filelist, monomerMass, outfile, nprocs, w_cut):
    return _vbw.run_vbw(again, k, mdfile, N, presaxsfile, Ncurves, curvesfile, filelist, monomerMass, outfile, nprocs, w_cut)
run_vbw = _vbw.run_vbw
# This file is compatible with both classic and new-style classes.


